import type {
  ChecklistItem,
  DaySchedule,
  DebtRecord,
  DiscoverTrip,
  Expense,
  Poll,
  QuickStats,
  TripCard,
  TripInvite,
  TripMember,
  TripNote,
} from "@/types/trip";

export const MOCK_MEMBERS: TripMember[] = [
  {
    id: "m1",
    name: "Minh Khôi",
    avatar: "https://api.dicebear.com/9.x/adventurer/svg?seed=Khoai",
    role: "admin",
    totalPaid: 4_500_000,
    totalOwed: 3_200_000,
    paymentStatus: "paid",
  },
  {
    id: "m2",
    name: "Thu Hà",
    avatar: "https://api.dicebear.com/9.x/adventurer/svg?seed=ThuHa",
    role: "member",
    totalPaid: 2_000_000,
    totalOwed: 3_200_000,
    paymentStatus: "unpaid",
  },
  {
    id: "m3",
    name: "Đức Anh",
    avatar: "https://api.dicebear.com/9.x/adventurer/svg?seed=DucAnh",
    role: "member",
    totalPaid: 3_800_000,
    totalOwed: 3_200_000,
    paymentStatus: "paid",
  },
  {
    id: "m4",
    name: "Thanh Trúc",
    avatar: "https://api.dicebear.com/9.x/adventurer/svg?seed=ThanhTruc",
    role: "member",
    totalPaid: 2_500_000,
    totalOwed: 3_200_000,
    paymentStatus: "unpaid",
  },
  {
    id: "m5",
    name: "Hoàng Nam",
    avatar: "https://api.dicebear.com/9.x/adventurer/svg?seed=HoangNam",
    role: "member",
    totalPaid: 3_200_000,
    totalOwed: 3_200_000,
    paymentStatus: "paid",
  },
];

export const MOCK_SCHEDULE: DaySchedule[] = [
  {
    day: 1,
    date: "2026-06-15",
    activities: [
      {
        id: "a1",
        time: "06:00",
        endTime: "08:30",
        title: "Bay từ HCM → Đà Nẵng",
        location: "Sân bay Tân Sơn Nhất → Đà Nẵng",
        type: "transport",
        cost: 1_200_000,
        note: "VietJet Air VJ601",
      },
      {
        id: "a2",
        time: "09:30",
        endTime: "10:30",
        title: "Check-in khách sạn",
        location: "Khách sạn Mường Thanh, Đà Nẵng",
        type: "stay",
        cost: 800_000,
        mapsUrl: "https://maps.google.com",
      },
      {
        id: "a3",
        time: "11:00",
        endTime: "12:30",
        title: "Ăn trưa - Mì Quảng Bà Vị",
        location: "166 Lê Đình Dương, Đà Nẵng",
        type: "food",
        cost: 250_000,
        note: "Quán nổi tiếng, nên đi sớm",
        mapsUrl: "https://maps.google.com",
      },
      {
        id: "a4",
        time: "14:00",
        endTime: "17:30",
        title: "Tham quan Bà Nà Hills",
        location: "Bà Nà Hills, Đà Nẵng",
        type: "sights",
        cost: 900_000,
        note: "Nhớ mang áo khoác vì trời lạnh trên núi",
        mapsUrl: "https://maps.google.com",
      },
      {
        id: "a5",
        time: "19:00",
        endTime: "21:00",
        title: "Hải sản Bé Mặn",
        location: "Bé Mặn, Đà Nẵng",
        type: "food",
        cost: 1_500_000,
        mapsUrl: "https://maps.google.com",
      },
    ],
  },
  {
    day: 2,
    date: "2026-06-16",
    activities: [
      {
        id: "a6",
        time: "07:00",
        endTime: "08:00",
        title: "Ăn sáng tại khách sạn",
        location: "Khách sạn Mường Thanh",
        type: "food",
        cost: 0,
      },
      {
        id: "a7",
        time: "09:00",
        endTime: "09:45",
        title: "Di chuyển đến Hội An",
        location: "Đà Nẵng → Hội An",
        type: "transport",
        cost: 300_000,
        note: "Thuê xe 7 chỗ",
      },
      {
        id: "a8",
        time: "10:00",
        endTime: "12:00",
        title: "Phố cổ Hội An",
        location: "Phố cổ Hội An",
        type: "sights",
        cost: 120_000,
        note: "Vé tham quan phố cổ 120k/người",
        mapsUrl: "https://maps.google.com",
      },
      {
        id: "a9",
        time: "12:30",
        endTime: "14:00",
        title: "Cao lầu & Cơm gà Hội An",
        location: "Quán Cao Lầu Thanh, Hội An",
        type: "food",
        cost: 350_000,
      },
      {
        id: "a10",
        time: "15:00",
        endTime: "17:00",
        title: "Làng gốm Thanh Hà",
        location: "Làng gốm Thanh Hà, Hội An",
        type: "sights",
        cost: 175_000,
        mapsUrl: "https://maps.google.com",
      },
      {
        id: "a11",
        time: "19:00",
        endTime: "21:00",
        title: "Thả đèn hoa đăng",
        location: "Sông Hoài, Hội An",
        type: "entertainment",
        cost: 100_000,
        note: "Mua đèn ở chợ đêm",
      },
    ],
  },
  {
    day: 3,
    date: "2026-06-17",
    activities: [
      {
        id: "a12",
        time: "06:00",
        endTime: "07:30",
        title: "Bình minh tại Mỹ Khê",
        location: "Bãi biển Mỹ Khê, Đà Nẵng",
        type: "sights",
        cost: 0,
      },
      {
        id: "a13",
        time: "08:00",
        endTime: "09:00",
        title: "Ăn sáng - Bánh xèo Bà Dưỡng",
        location: "K280/23 Hoàng Diệu, Đà Nẵng",
        type: "food",
        cost: 200_000,
      },
      {
        id: "a14",
        time: "10:00",
        endTime: "12:00",
        title: "Chùa Linh Ứng",
        location: "Bán đảo Sơn Trà, Đà Nẵng",
        type: "sights",
        cost: 0,
        mapsUrl: "https://maps.google.com",
      },
      {
        id: "a15",
        time: "14:00",
        endTime: "17:00",
        title: "Mua sắm tại Vincom Đà Nẵng",
        location: "Vincom Plaza Đà Nẵng",
        type: "shopping",
        cost: 2_000_000,
      },
      {
        id: "a16",
        time: "18:00",
        endTime: "20:00",
        title: "BBQ hải sản bãi biển",
        location: "Bãi biển Mỹ Khê",
        type: "food",
        cost: 1_800_000,
      },
    ],
  },
  {
    day: 4,
    date: "2026-06-18",
    activities: [
      {
        id: "a17",
        time: "08:00",
        endTime: "09:00",
        title: "Trả phòng khách sạn",
        location: "Khách sạn Mường Thanh",
        type: "stay",
        cost: 0,
      },
      {
        id: "a18",
        time: "09:30",
        endTime: "11:00",
        title: "Cầu Rồng & Bảo tàng Chăm",
        location: "Cầu Rồng, Đà Nẵng",
        type: "sights",
        cost: 80_000,
      },
      {
        id: "a19",
        time: "11:30",
        endTime: "13:00",
        title: "Ăn trưa trước khi bay",
        location: "Nhà hàng Madame Lân",
        type: "food",
        cost: 400_000,
      },
      {
        id: "a20",
        time: "15:00",
        endTime: "17:00",
        title: "Bay về HCM",
        location: "Sân bay Đà Nẵng → HCM",
        type: "transport",
        cost: 1_100_000,
      },
    ],
  },
];

export const MOCK_EXPENSES: Expense[] = [
  {
    id: "e1",
    title: "Vé máy bay đi",
    amount: 6_000_000,
    paidBy: "Minh Khôi",
    paidById: "m1",
    splitBetween: ["m1", "m2", "m3", "m4", "m5"],
    category: "transport",
    date: "2026-06-15",
  },
  {
    id: "e2",
    title: "Khách sạn 3 đêm",
    amount: 4_800_000,
    paidBy: "Đức Anh",
    paidById: "m3",
    splitBetween: ["m1", "m2", "m3", "m4", "m5"],
    category: "stay",
    date: "2026-06-15",
  },
  {
    id: "e3",
    title: "Mì Quảng Bà Vị",
    amount: 250_000,
    paidBy: "Thu Hà",
    paidById: "m2",
    splitBetween: ["m1", "m2", "m3", "m4", "m5"],
    category: "food",
    date: "2026-06-15",
  },
  {
    id: "e4",
    title: "Vé Bà Nà Hills",
    amount: 4_500_000,
    paidBy: "Minh Khôi",
    paidById: "m1",
    splitBetween: ["m1", "m2", "m3", "m4", "m5"],
    category: "ticket",
    date: "2026-06-15",
  },
  {
    id: "e5",
    title: "Hải sản Bé Mặn",
    amount: 1_500_000,
    paidBy: "Hoàng Nam",
    paidById: "m5",
    splitBetween: ["m1", "m2", "m3", "m4", "m5"],
    category: "food",
    date: "2026-06-15",
  },
  {
    id: "e6",
    title: "Thuê xe đi Hội An",
    amount: 300_000,
    paidBy: "Thanh Trúc",
    paidById: "m4",
    splitBetween: ["m1", "m2", "m3", "m4", "m5"],
    category: "transport",
    date: "2026-06-16",
  },
];

export const MOCK_DEBTS: DebtRecord[] = [
  {
    from: "Thu Hà",
    fromId: "m2",
    to: "Minh Khôi",
    toId: "m1",
    amount: 1_300_000,
  },
  {
    from: "Thanh Trúc",
    fromId: "m4",
    to: "Đức Anh",
    toId: "m3",
    amount: 700_000,
  },
  { from: "Thu Hà", fromId: "m2", to: "Đức Anh", toId: "m3", amount: 500_000 },
];

export const MOCK_POLLS: Poll[] = [
  {
    id: "p1",
    question: "Ăn trưa ngày 2 ở đâu?",
    createdBy: "Minh Khôi",
    isActive: true,
    options: [
      {
        id: "po1",
        label: "Cao lầu Thanh",
        description: "Quán lâu năm, nổi tiếng Hội An",
        votes: ["m1", "m3", "m5"],
      },
      {
        id: "po2",
        label: "Cơm gà Bà Buội",
        description: "Cơm gà ngon nhất phố",
        votes: ["m2", "m4"],
      },
      {
        id: "po3",
        label: "Bánh mì Phượng",
        description: "Bánh mì nổi tiếng thế giới",
        votes: [],
      },
    ],
  },
  {
    id: "p2",
    question: "Đi Bà Nà hay Sơn Trà trước?",
    createdBy: "Thu Hà",
    isActive: false,
    options: [
      { id: "po4", label: "Bà Nà Hills", votes: ["m1", "m2", "m3", "m5"] },
      { id: "po5", label: "Bán đảo Sơn Trà", votes: ["m4"] },
    ],
  },
];

export const MOCK_NOTES: TripNote[] = [
  {
    id: "n1",
    content:
      "🎒 Nhớ mang: kem chống nắng, áo khoác (Bà Nà lạnh), dép xỏ ngón, thuốc say xe\n\n📋 Check-in khách sạn từ 14h, nhưng có thể gửi đồ sớm.\n\n💡 Tips: Đổi tiền lẻ sẵn để mua đèn hoa đăng ở Hội An.",
    updatedBy: "Minh Khôi",
    updatedAt: "2026-06-10T08:30:00Z",
  },
];

export const MOCK_CHECKLIST: ChecklistItem[] = [
  {
    id: "c1",
    label: "Kem chống nắng SPF50+",
    isChecked: true,
    assignee: "Thu Hà",
  },
  { id: "c2", label: "Áo khoác mỏng", isChecked: true, assignee: "Minh Khôi" },
  { id: "c3", label: "Thuốc say xe", isChecked: false, assignee: "Thanh Trúc" },
  { id: "c4", label: "Sạc dự phòng", isChecked: true, assignee: "Đức Anh" },
  {
    id: "c5",
    label: "Máy ảnh + thẻ nhớ",
    isChecked: false,
    assignee: "Hoàng Nam",
  },
  { id: "c6", label: "In vé máy bay", isChecked: true, assignee: "Minh Khôi" },
  {
    id: "c7",
    label: "Booking khách sạn",
    isChecked: true,
    assignee: "Đức Anh",
  },
  { id: "c8", label: "Dép xỏ ngón", isChecked: false },
];

export const MOCK_TRIP_CARDS: TripCard[] = [
  {
    id: "t1",
    name: "Đà Nẵng - Hội An 4N3Đ",
    destination: "Đà Nẵng, Hội An",
    coverImage:
      "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=600&q=80",
    startDate: "2026-06-15",
    endDate: "2026-06-18",
    status: "upcoming",
    memberCount: 5,
    memberAvatars: MOCK_MEMBERS.slice(0, 4).map((m) => m.avatar),
  },
  {
    id: "t2",
    name: "Phú Quốc Beach Trip",
    destination: "Phú Quốc",
    coverImage:
      "https://images.unsplash.com/photo-1540979388-5b4b9b3c5e0d?w=600&q=80",
    startDate: "2026-03-01",
    endDate: "2026-03-04",
    status: "completed",
    memberCount: 4,
    memberAvatars: MOCK_MEMBERS.slice(0, 3).map((m) => m.avatar),
  },
  {
    id: "t3",
    name: "Đà Lạt - Langbiang",
    destination: "Đà Lạt",
    coverImage:
      "https://images.unsplash.com/photo-1586595147746-a0ce22e0tried?w=600&q=80",
    startDate: "2026-07-20",
    endDate: "2026-07-23",
    status: "upcoming",
    memberCount: 6,
    memberAvatars: MOCK_MEMBERS.slice(1, 4).map((m) => m.avatar),
  },
];

export const MOCK_INVITES: TripInvite[] = [
  {
    id: "inv1",
    tripName: "Sapa Trekking 3N2Đ",
    destination: "Sapa, Lào Cai",
    invitedBy: "Phương Linh",
    inviterAvatar:
      "https://api.dicebear.com/9.x/adventurer/svg?seed=PhuongLinh",
    startDate: "2026-08-10",
    endDate: "2026-08-12",
  },
];

export const MOCK_QUICK_STATS: QuickStats = {
  totalTrips: 8,
  totalCostThisYear: 28_500_000,
  nextDestination: "Đà Nẵng - Hội An",
  nextTripDate: "2026-06-15",
};

export const MOCK_DISCOVER_TRIPS: DiscoverTrip[] = [
  {
    id: "d1",
    name: "Đà Nẵng - Hội An 4N3Đ Tiết Kiệm",
    destination: "Đà Nẵng, Hội An",
    coverImage:
      "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=600&q=80",
    days: 4,
    // budget: 5_000_000,
    rating: 4.8,
    reviewCount: 124,
    authorName: "Travel Koi",
    authorAvatar: "https://api.dicebear.com/9.x/adventurer/svg?seed=TravelKoi",
    tags: ["Biển", "Ẩm thực", "Phố cổ"],
  },
  {
    id: "d2",
    name: "Phú Quốc All-in-one 5N4Đ",
    destination: "Phú Quốc",
    coverImage:
      "https://images.unsplash.com/photo-1540979388-5b4b9b3c5e0d?w=600&q=80",
    days: 5,
    // budget: 8_000_000,
    rating: 4.6,
    reviewCount: 89,
    authorName: "Wanderlust VN",
    authorAvatar: "https://api.dicebear.com/9.x/adventurer/svg?seed=Wanderlust",
    tags: ["Biển", "Resort", "Lặn biển"],
  },
  {
    id: "d3",
    name: "Đà Lạt Mùa Hoa 3N2Đ",
    destination: "Đà Lạt",
    coverImage:
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&q=80",
    days: 3,
    // budget: 3_500_000,
    rating: 4.9,
    reviewCount: 203,
    authorName: "Dalat Explorer",
    authorAvatar: "https://api.dicebear.com/9.x/adventurer/svg?seed=DalatExp",
    tags: ["Núi", "Hoa", "Cà phê"],
  },
  {
    id: "d4",
    name: "Nha Trang Beach Party 3N2Đ",
    destination: "Nha Trang",
    coverImage:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80",
    days: 3,
    // budget: 4_200_000,
    rating: 4.5,
    reviewCount: 67,
    authorName: "BeachLife",
    authorAvatar: "https://api.dicebear.com/9.x/adventurer/svg?seed=BeachLife",
    tags: ["Biển", "Tiệc", "Lặn biển"],
  },
  {
    id: "d5",
    name: "Hà Giang Loop 4N3Đ",
    destination: "Hà Giang",
    coverImage:
      "https://images.unsplash.com/photo-1528127269322-539801943592?w=600&q=80",
    days: 4,
    // budget: 4_000_000,
    rating: 4.9,
    reviewCount: 315,
    authorName: "Moto Adventure",
    authorAvatar: "https://api.dicebear.com/9.x/adventurer/svg?seed=MotoAdv",
    tags: ["Phượt", "Núi", "Văn hoá"],
  },
  {
    id: "d6",
    name: "Quy Nhơn Chill 3N2Đ",
    destination: "Quy Nhơn",
    coverImage:
      "https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=600&q=80",
    days: 3,
    // budget: 3_000_000,
    rating: 4.7,
    reviewCount: 98,
    authorName: "Quiet Trip",
    authorAvatar: "https://api.dicebear.com/9.x/adventurer/svg?seed=QuietTrip",
    tags: ["Biển", "Chill", "Ẩm thực"],
  },
];
